#!/bin/bash
# Build, package, and install LilTerminal.
#
#   ./make.sh              debug build   -> build/LilTerminal.app
#   ./make.sh --release    release build -> build/LilTerminal.app
#   ./make.sh --install    release build, installed to /Applications (replaces
#                          any previous version) and relaunched
#   ./make.sh --dmg        release build -> dist/LilTerminal-<version>.dmg
set -euo pipefail
cd "$(dirname "$0")"

VERSION="0.1"
APP="build/LilTerminal.app"
MODE="${1:-}"
CONFIG="debug"
[[ "$MODE" == "--release" || "$MODE" == "--install" || "$MODE" == "--dmg" ]] && CONFIG="release"

# --- icon -------------------------------------------------------------------
# Regenerated from source each time so the icon is never a stale binary blob.
mkdir -p build
if [[ ! -f build/LilTerminal.icns || Tools/makeicon.swift -nt build/LilTerminal.icns ]]; then
    swiftc -O -o build/makeicon Tools/makeicon.swift
    ./build/makeicon build/LilTerminal.iconset >/dev/null
    iconutil -c icns build/LilTerminal.iconset -o build/LilTerminal.icns
fi

# --- build ------------------------------------------------------------------
swift build -c "$CONFIG"
BIN="$(swift build -c "$CONFIG" --show-bin-path)/LilTerminal"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/LilTerminal"

# The session daemon ships beside the app binary. It owns the ptys, so shells
# survive the app quitting; the app launches it on demand.
DAEMON="$(swift build -c "$CONFIG" --show-bin-path)/lilterm-sessiond"
[ -f "$DAEMON" ] && cp "$DAEMON" "$APP/Contents/MacOS/lilterm-sessiond"
cp build/LilTerminal.icns "$APP/Contents/Resources/LilTerminal.icns"
# Keystroke samples, generated by Tools/make-typing-sounds.py.
cp -R Resources/Sounds "$APP/Contents/Resources/"

# Ghostty's VT engine ships as a dylib (see Package.swift for why it is not
# linked statically). The binary looks for it on an @executable_path rpath.
mkdir -p "$APP/Contents/Frameworks"
cp Vendor/ghostty-vt/lib/libghostty-vt.dylib "$APP/Contents/Frameworks/"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>              <string>LilTerminal</string>
    <key>CFBundleDisplayName</key>       <string>LilTerminal</string>
    <key>CFBundleIdentifier</key>        <string>app.lilterminal</string>
    <key>CFBundleExecutable</key>        <string>LilTerminal</string>
    <key>CFBundleIconFile</key>          <string>LilTerminal</string>
    <key>CFBundlePackageType</key>       <string>APPL</string>
    <key>CFBundleShortVersionString</key><string>$VERSION</string>
    <key>CFBundleVersion</key>           <string>$VERSION</string>
    <key>LSMinimumSystemVersion</key>    <string>14.0</string>
    <key>NSHighResolutionCapable</key>   <true/>
    <key>NSSupportsAutomaticTermination</key><false/>
    <!-- A terminal runs whatever you ask it to, so the permission prompts a
         command triggers are attributed to this app. Without a usage string
         macOS kills the process instead of asking. -->
    <key>NSMicrophoneUsageDescription</key>
    <string>A command you ran in the terminal is asking to use the microphone.</string>
    <key>NSCameraUsageDescription</key>
    <string>A command you ran in the terminal is asking to use the camera.</string>
    <key>NSDesktopFolderUsageDescription</key>
    <string>A command you ran in the terminal is asking to read your Desktop folder.</string>
    <key>NSDocumentsFolderUsageDescription</key>
    <string>A command you ran in the terminal is asking to read your Documents folder.</string>
    <key>NSDownloadsFolderUsageDescription</key>
    <string>A command you ran in the terminal is asking to read your Downloads folder.</string>
    <key>NSRemovableVolumesUsageDescription</key>
    <string>A command you ran in the terminal is asking to read a removable volume.</string>
    <key>NSAppleEventsUsageDescription</key>
    <string>A command you ran in the terminal is asking to control another app.</string>
</dict>
</plist>
PLIST

# The app is intentionally NOT sandboxed: reading other processes' CPU and
# memory via libproc is impossible inside the sandbox.
#
# Signing identity matters more than it looks. Ad-hoc signing gives the bundle a
# designated requirement of `cdhash H"..."` — the exact bytes of this build and
# nothing else. Every permission macOS remembers (Screen Recording, Microphone,
# Accessibility, Full Disk Access) is keyed to that requirement, so every
# rebuild looks like a different application: the switch stays on in System
# Settings while the new binary is quietly denied. Signing with a certificate
# instead pins the requirement to the certificate, and the grants survive.
#
# Set LILTERM_SIGN_ID to a name from `security find-identity -v -p codesigning`,
# or leave it unset for ad-hoc.
if [[ -n "${LILTERM_SIGN_ID:-}" ]]; then
    codesign --force --deep --options runtime --sign "$LILTERM_SIGN_ID" "$APP" \
        && echo "Signed with $LILTERM_SIGN_ID (permissions will persist across rebuilds)" \
        || { echo "error: signing with '$LILTERM_SIGN_ID' failed"; exit 1; }
else
    codesign --force --deep --sign - "$APP" 2>/dev/null || echo "note: ad-hoc signing skipped"
fi
echo "Built $APP"

# --- install ----------------------------------------------------------------
if [[ "$MODE" == "--install" ]]; then
    DEST="/Applications/LilTerminal.app"
    # Quit the running copy first: replacing a bundle underneath a live process
    # leaves it running stale code and can corrupt its state on next launch.
    if pgrep -x LilTerminal >/dev/null; then
        osascript -e 'tell application "LilTerminal" to quit' 2>/dev/null || true
        for _ in $(seq 1 25); do pgrep -x LilTerminal >/dev/null || break; sleep 0.2; done
        pkill -x LilTerminal 2>/dev/null || true
        sleep 0.5
    fi
    rm -rf "$DEST"
    cp -R "$APP" "$DEST"

    # An ad-hoc build has a new identity every time, so every permission macOS
    # remembered now points at a binary that no longer exists — the switch
    # still reads as on while the new build is denied, which looks exactly like
    # the permission being broken. Clearing them loses nothing that still
    # worked, and makes macOS ask again rather than deny silently.
    if [[ -z "${LILTERM_SIGN_ID:-}" ]]; then
        for service in ScreenCapture Microphone Camera Accessibility ListenEvent \
                       SystemPolicyDesktopFolder SystemPolicyDocumentsFolder \
                       SystemPolicyDownloadsFolder AppleEvents; do
            tccutil reset "$service" app.lilterminal >/dev/null 2>&1 || true
        done
        echo "note: ad-hoc signed — macOS sees each build as a new app, so stale"
        echo "      permission grants were cleared and will be asked for again."
        echo "      Export LILTERM_SIGN_ID=<identity> to keep them across builds."
    fi
    # Nudge Launch Services so the new icon and version are picked up.
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
        -f "$DEST" 2>/dev/null || true
    echo "Installed $DEST"
    open "$DEST"
fi

# --- dmg --------------------------------------------------------------------
if [[ "$MODE" == "--dmg" ]]; then
    mkdir -p dist
    STAGE="$(mktemp -d)"
    cp -R "$APP" "$STAGE/"
    # The Applications symlink is what makes the drag-to-install window work.
    ln -s /Applications "$STAGE/Applications"
    DMG="dist/LilTerminal-$VERSION.dmg"
    rm -f "$DMG"
    hdiutil create -volname "LilTerminal" -srcfolder "$STAGE" -ov -format UDZO "$DMG" >/dev/null
    rm -rf "$STAGE"
    echo "Packaged $DMG"
fi
